# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

- name: Install Carbonio
  import_playbook: "{{ install_path }}"
  when: install_path is defined and install_path != ''

- hosts: all
  order: inventory
  gather_facts: yes
  roles:
     - carbonio-singleserver



