# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

- hosts: all
  order: inventory
  gather_facts: yes
  roles:
     - carbonio-singleserver


