# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---

  - name: Change localconfig
    become: true
    become_method: su
    become_user: zextras
    command: 'zmlocalconfig -e ldap_common_threads=4 mailboxd_java_heap_size=2048'
    tags:
      - singleserver-reconfig-cmds

  - name: Change Global Config
    become: true
    become_method: su
    become_user: zextras
    command: 'zmprov mcf zimbraScheduledTaskMaxRetryDelay 10m zimbraGalMaxResults 50 zimbraGalSyncMaxConcurrentClients 1 zimbraScheduledTaskMaxRetries 5 zimbraSmtpHostname "127.0.0.1" zimbraSmtpPort 25'
    tags:
      - singleserver-reconfig-cmds

  - name: Change System parameters
    become: true
    become_method: su
    become_user: zextras
    command: 'zmprov ms {{inventory_hostname}} zimbraAdminImapImportNumThreads 2 zimbraDatabaseSlowSqlThreshold 4s zimbraHttpNumThreads 100 zimbraImapNumThreads 100 zimbraLmtpNumThreads 20 zimbraMilterNumThreads 50 zimbraPop3NumThreads 50 zimbraScheduledTaskNumThreads 5 zimbraAmavisMaxServers 5 zimbraCBPolicydMaxRequests 400 zimbraCBPolicydMaxServers 5
zimbraCBPolicydMaxSpareServers 3 zimbraClamAVMaxThreads 2 zimbraGalMaxResults "" zimbraGalSyncMaxConcurrentClients "" zimbraHttpDosFilterMaxRequestsPerSec 15 zimbraImapMaxConnections 100
zimbraMilterMaxConnections 2000 zimbraMtaMaxUse 100 zimbraPop3MaxConnections 100 zimbraScheduledTaskMaxRetries "" zimbraScheduledTaskMaxRetryDelay ""'
    tags:
      - singleserver-reconfig-cmds
      
  - name: Disable unwanted Carbonio services
    become: true
    become_method: su
    become_user: zextras
    command: 'zmprov ms {{inventory_hostname}} -zimbraServiceEnabled stats'
    tags:
      - singleserver-reconfig-cmds    
      
  - name: Reconfig MTA relay host
    become: true
    become_method: su
    become_user: zextras
    command: 'zmprov ms {{inventory_hostname}} zimbraSmtpHostname "" zimbraSmtpPort ""'
    tags:
      - singleserver-reconfig-cmds
      
      
  - name: Disable AS/AV
    become: true
    become_method: su
    become_user: zextras
    command: 'zmprov ms {{inventory_hostname}} zimbraSmtpHostname "" zimbraSmtpPort ""'
    tags:
      - singleserver-reconfig-cmds